defaults: &defaults
  host: localhost
  username: root
  password:
  adapter: mysql
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: spike_mongo_dev
